services:
  postgres:
    image: postgres:16-alpine
    container_name: shareliveloc-db
    environment:
      POSTGRES_USER: shareliveloc
      POSTGRES_PASSWORD: shareliveloc
      POSTGRES_DB: shareliveloc
    ports:
      - "5432:5432"
    volumes:
      - ./pgdata:/var/lib/postgresql/data
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U shareliveloc"]
      interval: 5s
      timeout: 5s
      retries: 5

  api:
    build:
      context: ./shareliveloc-api
      dockerfile: Dockerfile
    container_name: shareliveloc-api
    environment:
      DB_HOST: postgres
      DB_PORT: "5432"
      DB_USER: shareliveloc
      DB_PASSWORD: shareliveloc
      DB_NAME: shareliveloc
      APP_PACKAGE_NAME: com.ombapit.shareliveloc
      APP_SHA256_FINGERPRINTS: "0B:67:92:85:0F:A7:10:83:69:8F:E7:BF:08:6C:1F:0E:73:AF:26:5D:5E:46:3E:B9:CE:00:FD:52:C3:02:AB:C4,B1:DB:B7:58:7C:1C:66:5E:23:31:61:24:31:F1:24:F5:7C:DF:B9:1E:EE:E6:60:AF:CC:7A:10:8D:97:AF:52:21"
    ports:
      - "8080:8080"
    restart: unless-stopped
    depends_on:
      postgres:
        condition: service_healthy
